# Generated by Django 3.0.4 on 2020-03-20 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('issued_date', models.DateTimeField(auto_now=True)),
                ('hand_in_date', models.DateTimeField()),
                ('is_handed_in', models.BooleanField(default=False)),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_app.Magazine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
