# Generated by Django 3.0.4 on 2020-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20200327_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='due_date',
            field=models.DateField(),
        ),
    ]
